name: goalsapp2_CICD
on: 
    push:
        branches:
            - master
jobs:
    checkout_code:
        runs-os: ubuntu-latest
        steps:
            name: checkout code
            uses: actions/checkout@v4
            name: setup python environment
            uses: actions/setup-python@v5
            with:
                python-version: "3.13"
            name: setup virtual environment
            run: |
                python -m venv venvgoalsapp
                echo "virtual environment has been set up"
                source venvgoalsapp/bin/activate
                echo "you are now inside the virtual environment"
            name: cache dependencies
            uses: action/cache@v4
            with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }} 
            name: install dependencies
            run: |
                python3 -m pip install --upgrade pip &
                pip install -r requirments.txt

